//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;
using TTC2017.SmartGrids.SubstationStandard.Dataclasses;
using TTC2017.SmartGrids.SubstationStandard.LNNodes.DomainLNs;

namespace TTC2017.SmartGrids.SubstationStandard.LNNodes.LNGroupA
{
    
    
    /// <summary>
    /// The public interface for ARCO
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(ARCO))]
    [XmlDefaultImplementationTypeAttribute(typeof(ARCO))]
    public interface IARCO : IModelElement, IGroupA
    {
        
        /// <summary>
        /// The TapChg property
        /// </summary>
        IBSC TapChg
        {
            get;
            set;
        }
        
        /// <summary>
        /// The VOvSt property
        /// </summary>
        ISPS VOvSt
        {
            get;
            set;
        }
        
        /// <summary>
        /// The NeutAlm property
        /// </summary>
        ISPS NeutAlm
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DschBlk property
        /// </summary>
        ISPS DschBlk
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the TapChg property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TapChgChanging;
        
        /// <summary>
        /// Gets fired when the TapChg property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TapChgChanged;
        
        /// <summary>
        /// Gets fired before the VOvSt property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> VOvStChanging;
        
        /// <summary>
        /// Gets fired when the VOvSt property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> VOvStChanged;
        
        /// <summary>
        /// Gets fired before the NeutAlm property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> NeutAlmChanging;
        
        /// <summary>
        /// Gets fired when the NeutAlm property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> NeutAlmChanged;
        
        /// <summary>
        /// Gets fired before the DschBlk property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DschBlkChanging;
        
        /// <summary>
        /// Gets fired when the DschBlk property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DschBlkChanged;
    }
}

