//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;
using TTC2017.SmartGrids.CIM;
using TTC2017.SmartGrids.CIM.IEC61968.Assets;
using TTC2017.SmartGrids.CIM.IEC61968.PaymentMetering;
using TTC2017.SmartGrids.CIM.IEC61970.Core;
using TTC2017.SmartGrids.CIM.IEC61970.Informative.InfAssets;
using TTC2017.SmartGrids.CIM.IEC61970.Informative.InfCommon;
using TTC2017.SmartGrids.CIM.IEC61970.Informative.InfERPSupport;
using TTC2017.SmartGrids.CIM.IEC61970.Informative.InfGMLSupport;
using TTC2017.SmartGrids.CIM.IEC61970.Informative.InfLocations;
using TTC2017.SmartGrids.CIM.IEC61970.Informative.InfOperations;
using TTC2017.SmartGrids.CIM.IEC61970.Informative.InfWork;
using TTC2017.SmartGrids.CIM.IEC61970.Informative.MarketOperations;
using TTC2017.SmartGrids.CIM.IEC61970.Meas;

namespace TTC2017.SmartGrids.CIM.IEC61968.Common
{
    
    
    /// <summary>
    /// The public interface for DateTimeInterval
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(DateTimeInterval))]
    [XmlDefaultImplementationTypeAttribute(typeof(DateTimeInterval))]
    public interface IDateTimeInterval : IModelElement, IElement
    {
        
        /// <summary>
        /// The start property
        /// </summary>
        DateTime Start
        {
            get;
            set;
        }
        
        /// <summary>
        /// The end property
        /// </summary>
        DateTime End
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Start property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> StartChanging;
        
        /// <summary>
        /// Gets fired when the Start property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> StartChanged;
        
        /// <summary>
        /// Gets fired before the End property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EndChanging;
        
        /// <summary>
        /// Gets fired when the End property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EndChanged;
    }
}

