<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="outagePreventionJointarget" nsURI="http://www.transformation-tool-contest.eu/2017/smartGrids/VoltagePhaseMeasurements"
    nsPrefix="outagePreventionJt">
  <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.sourceModels" references="schema.ecore#/ COSEM.ecore#/ 61850.ecore#/"/>
  <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.traceModel" references="outagePrevention-trace.ecore#/"/>
  <eClassifiers xsi:type="ecore:EClass" name="PMUVoltageMeter" eSuperTypes="#//Asset #//EndDeviceAsset">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.left" references="schema.ecore#//IEC61968/Metering/MeterAsset"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.right" references="61850.ecore#//LNNodes/LNGroupM/MMXU"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.jointrace" references="outagePrevention-trace.ecore#//join_MeterAsset_MMXU_PMUVoltageMeter"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="order" value="1"/>
      <details key="operator" value="thetajoin"/>
      <details key="condition" value="CIM.IEC61968.Metering.MeterAsset = substationStandard.LNNodes.LNGroupM.MMXU.NamePlt.IdNs"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mRID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="A Model Authority issues mRIDs. Given that each Model Authority has a unique id and this id is part of the mRID, then the mRID is globally unique."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="A Model Authority issues mRIDs. Given that each Model Authority has a unique id and this id is part of the mRID, then the mRID is globally unique."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepattributes"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61968/Metering/MeterAsset"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.attribute" references="schema.ecore#//IEC61970/Core/IdentifiedObject/mRID"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.context" references="#//PMUVoltageMeter"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VoltageAMag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepcalculated"/>
        <details key="formula" value="substationStandard.LNNodes.LNGroupM.MMXU.PhV.phsA.cVal.mag.f"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VoltageAAng" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepcalculated"/>
        <details key="formula" value="substationStandard.LNNodes.LNGroupM.MMXU.PhV.phsA.cVal.ang.f"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VoltageBMag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepcalculated"/>
        <details key="formula" value="substationStandard.LNNodes.LNGroupM.MMXU.PhV.phsB.cVal.mag.f"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VoltageBAng" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepcalculated"/>
        <details key="formula" value="substationStandard.LNNodes.LNGroupM.MMXU.PhV.phsB.cVal.ang.f"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VoltageCMag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepcalculated"/>
        <details key="formula" value="substationStandard.LNNodes.LNGroupM.MMXU.PhV.phsC.cVal.mag.f"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VoltageCAng" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepcalculated"/>
        <details key="formula" value="substationStandard.LNNodes.LNGroupM.MMXU.PhV.phsC.cVal.ang.f"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VoltageNeutMag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepcalculated"/>
        <details key="formula" value="substationStandard.LNNodes.LNGroupM.MMXU.PhV.neut.cVal.mag.f"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VoltageNeutAng" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepcalculated"/>
        <details key="formula" value="substationStandard.LNNodes.LNGroupM.MMXU.PhV.neut.cVal.ang.f"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VoltageNetMag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepcalculated"/>
        <details key="formula" value="substationStandard.LNNodes.LNGroupM.MMXU.PhV.net.cVal.mag.f"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VoltageNetAng" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepcalculated"/>
        <details key="formula" value="substationStandard.LNNodes.LNGroupM.MMXU.PhV.net.cVal.ang.f"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VoltageResMag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepcalculated"/>
        <details key="formula" value="substationStandard.LNNodes.LNGroupM.MMXU.PhV.res.cVal.mag.f"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VoltageResAng" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepcalculated"/>
        <details key="formula" value="substationStandard.LNNodes.LNGroupM.MMXU.PhV.res.cVal.ang.f"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrivateMeterVoltage" eSuperTypes="#//Asset #//EndDeviceAsset">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.left" references="schema.ecore#//IEC61968/Metering/MeterAsset"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.right" references="COSEM.ecore#//PhysicalDevice"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.jointrace" references="outagePrevention-trace.ecore#//join_MeterAsset_PhysicalDevice_PrivateMeterVoltage"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="order" value="2"/>
      <details key="operator" value="thetajoin"/>
      <details key="condition" value="CIM.IEC61968.Metering.MeterAsset.mRID = COSEM.PhysicalDevice.ID"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepattributes"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="COSEM.ecore#//PhysicalDevice"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.attribute" references="COSEM.ecore#//PhysicalDevice/ID"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.context" references="#//PrivateMeterVoltage"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VoltageA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepcalculated"/>
        <details key="formula" value="COSEM.PhysicalDevice.ElectricityValues.VoltageL1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VoltageB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepcalculated"/>
        <details key="formula" value="COSEM.PhysicalDevice.ElectricityValues.VoltageL2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VoltageC" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepcalculated"/>
        <details key="formula" value="COSEM.PhysicalDevice.ElectricityValues.VoltageL3"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61968/Assets/Asset"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepsupertype"/>
      <details key="order" value="3"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Location" eType="#//Location">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="Location of this asset."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="Location of this asset."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepoutgoing"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.oftype" references="schema.ecore#//IEC61968/Common/Location"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reference" references="schema.ecore#//IEC61968/Assets/Asset/Location"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61968/Assets/Asset"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_Location_Location_Location"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61968/Common/Location"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepoutgoing"/>
      <details key="order" value="4"/>
    </eAnnotations>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_Location_Location_Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Position" eType="#//PositionPoint">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepoutgoing"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.oftype" references="schema.ecore#//IEC61968/Common/PositionPoint"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reference" references="schema.ecore#//IEC61968/Common/Location/Position"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61968/Common/Location"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_PositionPoint_PositionPoint_Position"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PowerSystemResources" upperBound="-1"
        eType="#//PowerSystemResource">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="All power system resources at this location."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="All power system resources at this location."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepoutgoing"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.oftype" references="schema.ecore#//IEC61970/Core/PowerSystemResource"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reference" references="schema.ecore#//IEC61968/Common/Location/PowerSystemResources"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61968/Common/Location"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_PowerSystemResource_PowerSystemResource_PowerSystemResources"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PositionPoint">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61968/Common/PositionPoint"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepoutgoing"/>
      <details key="order" value="5"/>
    </eAnnotations>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_PositionPoint_PositionPoint_Position"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xPosition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="X axis position."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="X axis position."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepattributes"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61968/Common/PositionPoint"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.attribute" references="schema.ecore#//IEC61968/Common/PositionPoint/xPosition"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.context" references="#//PositionPoint"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yPosition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="Y axis position."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="Y axis position."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepattributes"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61968/Common/PositionPoint"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.attribute" references="schema.ecore#//IEC61968/Common/PositionPoint/yPosition"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.context" references="#//PositionPoint"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zPosition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="(if applicable) Z axis position."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="(if applicable) Z axis position."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepattributes"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61968/Common/PositionPoint"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.attribute" references="schema.ecore#//IEC61968/Common/PositionPoint/zPosition"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.context" references="#//PositionPoint"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PowerSystemResource">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/Core/PowerSystemResource"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepoutgoing"/>
      <details key="order" value="6"/>
    </eAnnotations>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_PowerSystemResource_PowerSystemResource_PowerSystemResources"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConductingEquipment" eSuperTypes="#//PowerSystemResource">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/Core/ConductingEquipment"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepsubtype"/>
      <details key="order" value="7"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Terminals" upperBound="-1"
        eType="#//Terminal">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="ConductingEquipment has 1 or 2 terminals that may be connected to other ConductingEquipment terminals via ConnectivityNodes"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="ConductingEquipment has 1 or 2 terminals that may be connected to other ConductingEquipment terminals via ConnectivityNodes"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepoutgoing"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.oftype" references="schema.ecore#//IEC61970/Core/Terminal"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reference" references="schema.ecore#//IEC61970/Core/ConductingEquipment/Terminals"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/Core/ConductingEquipment"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_Terminal_Terminal_Terminals"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Terminal">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/Core/Terminal"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepoutgoing"/>
      <details key="order" value="8"/>
    </eAnnotations>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_Terminal_Terminal_Terminals"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TieFlow" upperBound="-1"
        eType="#//TieFlow">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="The control area tie flows to which this terminal associates."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="The control area tie flows to which this terminal associates."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepoutgoing"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.oftype" references="schema.ecore#//IEC61970/ControlArea/TieFlow"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reference" references="schema.ecore#//IEC61970/Core/Terminal/TieFlow"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/Core/Terminal"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_TieFlow_TieFlow_TieFlow"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TieFlow">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/ControlArea/TieFlow"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepoutgoing"/>
      <details key="order" value="9"/>
    </eAnnotations>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_TieFlow_TieFlow_TieFlow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ControlArea" eType="#//ControlArea">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="The control area of the tie flows."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="The control area of the tie flows."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepoutgoing"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.oftype" references="schema.ecore#//IEC61970/ControlArea/ControlArea"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reference" references="schema.ecore#//IEC61970/ControlArea/TieFlow/ControlArea"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/ControlArea/TieFlow"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_ControlArea_ControlArea_ControlArea"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlArea">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/ControlArea/ControlArea"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepoutgoing"/>
      <details key="order" value="19"/>
    </eAnnotations>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_ControlArea_ControlArea_ControlArea"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mRID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="A Model Authority issues mRIDs. Given that each Model Authority has a unique id and this id is part of the mRID, then the mRID is globally unique."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="A Model Authority issues mRIDs. Given that each Model Authority has a unique id and this id is part of the mRID, then the mRID is globally unique."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepattributes"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/ControlArea/ControlArea"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.attribute" references="schema.ecore#//IEC61970/Core/IdentifiedObject/mRID"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.context" references="#//ControlArea"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndDeviceAsset">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61968/Metering/EndDeviceAsset"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepsupertype"/>
      <details key="order" value="11"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiceDeliveryPoint" eType="#//ServiceDeliveryPoint">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="Service delivery point to which this end device asset belongs."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="Service delivery point to which this end device asset belongs."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepoutgoing"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.oftype" references="schema.ecore#//IEC61968/Metering/ServiceDeliveryPoint"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reference" references="schema.ecore#//IEC61968/Metering/EndDeviceAsset/ServiceDeliveryPoint"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61968/Metering/EndDeviceAsset"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_ServiceDeliveryPoint_ServiceDeliveryPoint_ServiceDeliveryPoint"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceDeliveryPoint">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61968/Metering/ServiceDeliveryPoint"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepoutgoing"/>
      <details key="order" value="12"/>
    </eAnnotations>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_ServiceDeliveryPoint_ServiceDeliveryPoint_ServiceDeliveryPoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EnergyConsumer" eType="#//EnergyConsumer">
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepoutgoing"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.oftype" references="schema.ecore#//IEC61970/Wires/EnergyConsumer"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reference" references="schema.ecore#//IEC61968/Metering/ServiceDeliveryPoint/EnergyConsumer"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61968/Metering/ServiceDeliveryPoint"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_EnergyConsumer_EnergyConsumer_EnergyConsumer"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnergyConsumer">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/Wires/EnergyConsumer"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepoutgoing"/>
      <details key="order" value="13"/>
    </eAnnotations>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_EnergyConsumer_EnergyConsumer_EnergyConsumer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mRID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="A Model Authority issues mRIDs. Given that each Model Authority has a unique id and this id is part of the mRID, then the mRID is globally unique."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="A Model Authority issues mRIDs. Given that each Model Authority has a unique id and this id is part of the mRID, then the mRID is globally unique."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepattributes"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/Wires/EnergyConsumer"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.attribute" references="schema.ecore#//IEC61970/Core/IdentifiedObject/mRID"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.context" references="#//EnergyConsumer"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConformLoad" eSuperTypes="#//EnergyConsumer">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/LoadModel/ConformLoad"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepsubtype"/>
      <details key="order" value="14"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LoadGroup" eType="#//ConformLoadGroup">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="Group of this ConformLoad."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="Group of this ConformLoad."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepoutgoing"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.oftype" references="schema.ecore#//IEC61970/LoadModel/ConformLoadGroup"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reference" references="schema.ecore#//IEC61970/LoadModel/ConformLoad/LoadGroup"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/LoadModel/ConformLoad"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_ConformLoadGroup_ConformLoadGroup_LoadGroup"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConformLoadGroup" eSuperTypes="#//LoadGroup">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/LoadModel/ConformLoadGroup"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepoutgoing"/>
      <details key="order" value="15"/>
    </eAnnotations>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_ConformLoadGroup_ConformLoadGroup_LoadGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadGroup">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/LoadModel/LoadGroup"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepsupertype"/>
      <details key="order" value="16"/>
    </eAnnotations>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepsupertype"/>
      <details key="order" value="22"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SubLoadArea" eType="#//SubLoadArea">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="The SubLoadArea where the Loadgroup belongs."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="The SubLoadArea where the Loadgroup belongs."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepoutgoing"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.oftype" references="schema.ecore#//IEC61970/LoadModel/SubLoadArea"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reference" references="schema.ecore#//IEC61970/LoadModel/LoadGroup/SubLoadArea"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/LoadModel/LoadGroup"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_SubLoadArea_SubLoadArea_SubLoadArea"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubLoadArea">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/LoadModel/SubLoadArea"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepoutgoing"/>
      <details key="order" value="17"/>
    </eAnnotations>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_SubLoadArea_SubLoadArea_SubLoadArea"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LoadArea" eType="#//LoadArea">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="The LoadArea where the SubLoadArea belongs."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="The LoadArea where the SubLoadArea belongs."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepoutgoing"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.oftype" references="schema.ecore#//IEC61970/LoadModel/LoadArea"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reference" references="schema.ecore#//IEC61970/LoadModel/SubLoadArea/LoadArea"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/LoadModel/SubLoadArea"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_LoadArea_LoadArea_LoadArea"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadArea">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/LoadModel/LoadArea"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepoutgoing"/>
      <details key="order" value="18"/>
    </eAnnotations>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_LoadArea_LoadArea_LoadArea"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ControlArea" eType="#//ControlArea">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="The control area specification that is used for the load forecast."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="The control area specification that is used for the load forecast."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepoutgoing"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.oftype" references="schema.ecore#//IEC61970/ControlArea/ControlArea"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reference" references="schema.ecore#//IEC61970/LoadModel/EnergyArea/ControlArea"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/LoadModel/LoadArea"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonConformLoad" eSuperTypes="#//EnergyConsumer">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/LoadModel/NonConformLoad"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepsubtype"/>
      <details key="order" value="20"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LoadGroup" eType="#//NonConformLoadGroup">
      <eAnnotations source="http://iec.ch/TC57/2009/CIM-schema-cim14">
        <details key="Documentation" value="Group of this ConformLoad."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Documentation" value="Group of this ConformLoad."/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
        <details key="operator" value="keepoutgoing"/>
      </eAnnotations>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.oftype" references="schema.ecore#//IEC61970/LoadModel/NonConformLoadGroup"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reference" references="schema.ecore#//IEC61970/LoadModel/NonConformLoad/LoadGroup"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/LoadModel/NonConformLoad"/>
      <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_NonConformLoadGroup_NonConformLoadGroup_LoadGroup"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonConformLoadGroup" eSuperTypes="#//LoadGroup">
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace" references="schema.ecore#//IEC61970/LoadModel/NonConformLoadGroup"/>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.createdBy">
      <details key="operator" value="keepoutgoing"/>
      <details key="order" value="21"/>
    </eAnnotations>
    <eAnnotations source="edu.kit.ipd.sdq.mdsd.mj.classTrace.reftrace" references="outagePrevention-trace.ecore#//ref_NonConformLoadGroup_NonConformLoadGroup_LoadGroup"/>
  </eClassifiers>
</ecore:EPackage>
