//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;
using TTC2017.SmartGrids.SubstationStandard.Dataclasses;
using TTC2017.SmartGrids.SubstationStandard.LNNodes.DomainLNs;

namespace TTC2017.SmartGrids.SubstationStandard.LNNodes.LNGroupR
{
    
    
    /// <summary>
    /// The public interface for RSYN
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(RSYN))]
    [XmlDefaultImplementationTypeAttribute(typeof(RSYN))]
    public interface IRSYN : IModelElement, IGroupR
    {
        
        /// <summary>
        /// The RHz property
        /// </summary>
        ISPC RHz
        {
            get;
            set;
        }
        
        /// <summary>
        /// The LHz property
        /// </summary>
        ISPC LHz
        {
            get;
            set;
        }
        
        /// <summary>
        /// The RV property
        /// </summary>
        ISPC RV
        {
            get;
            set;
        }
        
        /// <summary>
        /// The LV property
        /// </summary>
        ISPC LV
        {
            get;
            set;
        }
        
        /// <summary>
        /// The Rel property
        /// </summary>
        ISPS Rel
        {
            get;
            set;
        }
        
        /// <summary>
        /// The Vlnd property
        /// </summary>
        ISPS Vlnd
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AngInd property
        /// </summary>
        ISPS AngInd
        {
            get;
            set;
        }
        
        /// <summary>
        /// The HzInd property
        /// </summary>
        ISPS HzInd
        {
            get;
            set;
        }
        
        /// <summary>
        /// The SynPrg property
        /// </summary>
        ISPS SynPrg
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DifVClc property
        /// </summary>
        IMV DifVClc
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DifAngClc property
        /// </summary>
        IMV DifAngClc
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DifV property
        /// </summary>
        IASG DifV
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DifHz property
        /// </summary>
        IASG DifHz
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DifAng property
        /// </summary>
        IASG DifAng
        {
            get;
            set;
        }
        
        /// <summary>
        /// The LivDeaMod property
        /// </summary>
        IING LivDeaMod
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DeaLinVal property
        /// </summary>
        IASG DeaLinVal
        {
            get;
            set;
        }
        
        /// <summary>
        /// The LivLinVal property
        /// </summary>
        IASG LivLinVal
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DeaBusVal property
        /// </summary>
        IASG DeaBusVal
        {
            get;
            set;
        }
        
        /// <summary>
        /// The PlsTmms property
        /// </summary>
        IING PlsTmms
        {
            get;
            set;
        }
        
        /// <summary>
        /// The BkrTmms property
        /// </summary>
        IING BkrTmms
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the RHz property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> RHzChanging;
        
        /// <summary>
        /// Gets fired when the RHz property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> RHzChanged;
        
        /// <summary>
        /// Gets fired before the LHz property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> LHzChanging;
        
        /// <summary>
        /// Gets fired when the LHz property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> LHzChanged;
        
        /// <summary>
        /// Gets fired before the RV property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> RVChanging;
        
        /// <summary>
        /// Gets fired when the RV property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> RVChanged;
        
        /// <summary>
        /// Gets fired before the LV property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> LVChanging;
        
        /// <summary>
        /// Gets fired when the LV property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> LVChanged;
        
        /// <summary>
        /// Gets fired before the Rel property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> RelChanging;
        
        /// <summary>
        /// Gets fired when the Rel property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> RelChanged;
        
        /// <summary>
        /// Gets fired before the Vlnd property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> VlndChanging;
        
        /// <summary>
        /// Gets fired when the Vlnd property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> VlndChanged;
        
        /// <summary>
        /// Gets fired before the AngInd property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AngIndChanging;
        
        /// <summary>
        /// Gets fired when the AngInd property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AngIndChanged;
        
        /// <summary>
        /// Gets fired before the HzInd property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> HzIndChanging;
        
        /// <summary>
        /// Gets fired when the HzInd property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> HzIndChanged;
        
        /// <summary>
        /// Gets fired before the SynPrg property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SynPrgChanging;
        
        /// <summary>
        /// Gets fired when the SynPrg property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SynPrgChanged;
        
        /// <summary>
        /// Gets fired before the DifVClc property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DifVClcChanging;
        
        /// <summary>
        /// Gets fired when the DifVClc property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DifVClcChanged;
        
        /// <summary>
        /// Gets fired before the DifAngClc property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DifAngClcChanging;
        
        /// <summary>
        /// Gets fired when the DifAngClc property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DifAngClcChanged;
        
        /// <summary>
        /// Gets fired before the DifV property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DifVChanging;
        
        /// <summary>
        /// Gets fired when the DifV property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DifVChanged;
        
        /// <summary>
        /// Gets fired before the DifHz property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DifHzChanging;
        
        /// <summary>
        /// Gets fired when the DifHz property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DifHzChanged;
        
        /// <summary>
        /// Gets fired before the DifAng property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DifAngChanging;
        
        /// <summary>
        /// Gets fired when the DifAng property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DifAngChanged;
        
        /// <summary>
        /// Gets fired before the LivDeaMod property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> LivDeaModChanging;
        
        /// <summary>
        /// Gets fired when the LivDeaMod property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> LivDeaModChanged;
        
        /// <summary>
        /// Gets fired before the DeaLinVal property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DeaLinValChanging;
        
        /// <summary>
        /// Gets fired when the DeaLinVal property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DeaLinValChanged;
        
        /// <summary>
        /// Gets fired before the LivLinVal property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> LivLinValChanging;
        
        /// <summary>
        /// Gets fired when the LivLinVal property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> LivLinValChanged;
        
        /// <summary>
        /// Gets fired before the DeaBusVal property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DeaBusValChanging;
        
        /// <summary>
        /// Gets fired when the DeaBusVal property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DeaBusValChanged;
        
        /// <summary>
        /// Gets fired before the PlsTmms property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> PlsTmmsChanging;
        
        /// <summary>
        /// Gets fired when the PlsTmms property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> PlsTmmsChanged;
        
        /// <summary>
        /// Gets fired before the BkrTmms property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> BkrTmmsChanging;
        
        /// <summary>
        /// Gets fired when the BkrTmms property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> BkrTmmsChanged;
    }
}

