<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="outageDetectionJointarget" nsURI="platform:/plugin/rgse.ttc17.metamodels.trg.outage.detection/model/outageDetection-target.ecore"
    nsPrefix="outageDtJt">
  <eClassifiers xsi:type="ecore:EClass" name="EnergyConsumer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Location" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Reachability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PowerA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ControlAreaID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Position" eType="#//PositionPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PositionPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xPosition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yPosition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zPosition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
