//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;
using TTC2017.SmartGrids.SubstationStandard.Enumerations;

namespace TTC2017.SmartGrids.SubstationStandard.Dataclasses
{
    
    
    /// <summary>
    /// The public interface for DetailQual
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(DetailQual))]
    [XmlDefaultImplementationTypeAttribute(typeof(DetailQual))]
    public interface IDetailQual : IModelElement
    {
        
        /// <summary>
        /// The overflow property
        /// </summary>
        Nullable<bool> Overflow
        {
            get;
            set;
        }
        
        /// <summary>
        /// The outOfRange property
        /// </summary>
        Nullable<bool> OutOfRange
        {
            get;
            set;
        }
        
        /// <summary>
        /// The badReference property
        /// </summary>
        Nullable<bool> BadReference
        {
            get;
            set;
        }
        
        /// <summary>
        /// The oscillatory property
        /// </summary>
        Nullable<bool> Oscillatory
        {
            get;
            set;
        }
        
        /// <summary>
        /// The failure property
        /// </summary>
        Nullable<bool> Failure
        {
            get;
            set;
        }
        
        /// <summary>
        /// The oldData property
        /// </summary>
        Nullable<bool> OldData
        {
            get;
            set;
        }
        
        /// <summary>
        /// The inconsistent property
        /// </summary>
        Nullable<bool> Inconsistent
        {
            get;
            set;
        }
        
        /// <summary>
        /// The inaccurate property
        /// </summary>
        Nullable<bool> Inaccurate
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Overflow property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OverflowChanging;
        
        /// <summary>
        /// Gets fired when the Overflow property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OverflowChanged;
        
        /// <summary>
        /// Gets fired before the OutOfRange property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OutOfRangeChanging;
        
        /// <summary>
        /// Gets fired when the OutOfRange property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OutOfRangeChanged;
        
        /// <summary>
        /// Gets fired before the BadReference property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> BadReferenceChanging;
        
        /// <summary>
        /// Gets fired when the BadReference property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> BadReferenceChanged;
        
        /// <summary>
        /// Gets fired before the Oscillatory property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OscillatoryChanging;
        
        /// <summary>
        /// Gets fired when the Oscillatory property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OscillatoryChanged;
        
        /// <summary>
        /// Gets fired before the Failure property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FailureChanging;
        
        /// <summary>
        /// Gets fired when the Failure property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FailureChanged;
        
        /// <summary>
        /// Gets fired before the OldData property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OldDataChanging;
        
        /// <summary>
        /// Gets fired when the OldData property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OldDataChanged;
        
        /// <summary>
        /// Gets fired before the Inconsistent property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> InconsistentChanging;
        
        /// <summary>
        /// Gets fired when the Inconsistent property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> InconsistentChanged;
        
        /// <summary>
        /// Gets fired before the Inaccurate property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> InaccurateChanging;
        
        /// <summary>
        /// Gets fired when the Inaccurate property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> InaccurateChanged;
    }
}

